sr: 16000
spectrogram:
  _target_: src.datasets.utils.MelSpectrogram
  sr: 16000
  win_length: 1024
  hop_length: 256
  n_fft: 1024
  f_min: 0
  f_max: 8000
  n_mels: 80
  power:  1.0
  pad_value: -11.5129251
log_spec: true