stem_params:
  - in_channels: 1
    out_channels: 64
    kernel_size:
      - 5
      - 1
    stride:
      - 3
      - 1
    padding:
      - 2
      - 0
  - in_channels: 64
    out_channels: 128
    kernel_size:
      - 5
      - 1
    stride:
      - 3
      - 1
    padding:
      - 2
      - 0
  - in_channels: 128
    out_channels: 256
    kernel_size:
      - 5
      - 1
    stride:
      - 3
      - 1
    padding:
      - 2
      - 0
  - in_channels: 256
    out_channels: 512
    kernel_size:
      - 5
      - 1
    stride:
      - 3
      - 1
    padding:
      - 2
      - 0
poststem_params:
  in_channels: 512
  out_channels: 1024
  kernel_size:
    - 5
    - 1
  padding: same
epilog_params:
  in_channels: 1024
  out_channels: 1
  kernel_size:
    - 3
    - 1
  padding: same