name: one_batch_full_hifi_plus_official
n_gpu: 1
preprocessing:
  sr: 16000
  spectrogram:
    type: MelSpectrogram
    args: {}
  log_spec: true
augmentations:
  wave: []
  spectrogram: []
generator:
  type: A2AHiFiPlusGeneratorV2
  args: {}

data:
  train:
    batch_size: 24
    num_workers: 0
    datasets:
      - type: VCTKDataset
        args:
          part: testset
          max_audio_length: 32768
          limit: 24
  val:
    batch_size: 24
    num_workers: 0
    datasets:
      - type: VCTKDataset
        args:
          part: testset
          max_audio_length: 32768
          limit: 24


trainer:
  epochs: 2000
  save_dir: saved/
  save_period: 1000
  verbosity: 2
  log_media: 5
  monitor: min val_loss
  early_stop: 100
  visualize: wandb
  wandb_project: hifi_plusplus
