name: HiFi++
n_gpu: 1
preprocessing:
  sr: 16000
  spectrogram:
    type: MelSpectrogram
    args: {}
  log_spec: true

defaults:
  - generator: generator
  - discriminator: discriminator
  - writer: wandb
  - metrics: enhancement
  - data: full_data
  - dataloader: example
  - transforms: example
  - _self_

gen_optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
dis_optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]

gen_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999
dis_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

gen_loss:
  _target_: src.loss.GeneratorLoss
  mel_lambda: 45
  fm_lambda: 2
dis_loss:
  _target_: src.loss.DiscriminatorLoss

trainer:
  epochs: 20
  save_dir: saved/
  save_period: 5
  verbosity: 2
  log_media: 5
  monitor: min val_loss
  early_stop: 100
  visualize: wandb
  wandb_project: hifi_plusplus
