name: one_batch_hifi_full
defaults:
  - generator: generator
  - discriminator: discriminator
  - writer: wandb
  - metrics: enhancement
  - datasets: one_batch_data
  - preprocessing: default
  - dataloader: default
  - _self_

gen_optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
dis_optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]

gen_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999
dis_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

gen_loss:
  _target_: src.loss.GeneratorLoss
  mel_lambda: 45
  fm_lambda: 2
dis_loss:
  _target_: src.loss.DiscriminatorLoss

trainer:
  epochs: 2000
  save_dir: saved/
  save_period: 1000
  verbosity: 2
  log_media: 5
  monitor: min val_loss
  early_stop: 100
  visualize: wandb
  random_seed: 123
  device: auto
  n_gpu: 1
  wandb_project: hifi_plusplus